# Generated by Django 6.0.7 on 2026-07-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_alter_testimonialmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodel',
            name='image',
            field=models.ImageField(default='testimonials/testimonal default.png', upload_to='media/testimonials'),
        ),
    ]
